name: example
description: Example app demonstrating the font_preview Flutter package.

publish_to: none

version: 1.0.0+1

environment:
  sdk: ^3.10.0
  flutter: '>=3.38.0'

dependencies:
  flutter:
    sdk: flutter
  font_preview:
    path: ../
  google_fonts: ^8.2.1
  cupertino_icons: ^1.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/google_fonts/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Light.ttf
          weight: 300
        - asset: assets/fonts/Ubuntu-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Ubuntu-Regular.ttf
          weight: 400
        - asset: assets/fonts/Ubuntu-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Ubuntu-Medium.ttf
          weight: 500
        - asset: assets/fonts/Ubuntu-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Ubuntu-Bold.ttf
          weight: 700
        - asset: assets/fonts/Ubuntu-BoldItalic.ttf
          weight: 700
          style: italic
