name: font_preview
description: A package to inspect, compare and preview fonts that are being used in Flutter apps
version: 0.2.1
homepage: https://github.com/easazade/font_preview
repository: https://github.com/easazade/font_preview

environment:
  sdk: ^3.8.0
  flutter: '>=3.32.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  fonts:
    - family: fallback_font
      fonts:
        - asset: lib/src/assets/fallback_font/BungeeShade-Regular.ttf

